version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-notification-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xc590d2jm143"
s3_prefix = "app-notification-service"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

parameter_overrides = ""


