AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notifications-service

  SAM Template for notification service
  
Parameters:
  ProjectName:
    Type: String
    Default: app-notification-service
  SecurityGroupID:
    Type: String
    NoEcho: true
  SubnetID:
    Type: String
    NoEcho: true
  RedisEndpoint:
    Type: String
    NoEcho: true
  RedisPort:
    Type: String
    NoEcho: true

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  NotifyEndpointUsage:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: notify-endpoint-usage
      CodeUri: app/
      Handler: dist/functions/notify-endpoint-usage/app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          REDIS_HOST: !Ref RedisEndpoint
          REDIS_PORT: !Ref RedisPort
      Policies:
        - "AWSLambdaVPCAccessExecutionRole"
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupID
        SubnetIds:
          - !Ref SubnetID
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NotifyEndpointUsage:
    Description: "Notify Endpoint Usage Lambda Function ARN"
    Value: !GetAtt NotifyEndpointUsage.Arn
