AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app-notification-service

  SAM Template for notification service
  
Parameters:
  ProjectName:
    Type: String
    Default: app-notification-service
  SecurityGroupID:
    Type: String
    NoEcho: true
  SubnetIDs:
    Type: CommaDelimitedList
    NoEcho: true
  RedisEndpoint:
    Type: String
    NoEcho: true
  RedisPort:
    Type: String
    NoEcho: true
  MongoDBConnectionString:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 30

Resources:
  NotifyEndpointUsage:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: notify-endpoint-usage
      Description: Notifies of endpoints which overrun the allowed stake
      CodeUri: app/
      Handler: notify-endpoint-usage/app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          REDIS_HOST: !Ref RedisEndpoint
          REDIS_PORT: !Ref RedisPort
          MONGODB_CONN_STR: !Ref MongoDBConnectionString
      Policies:
        - "AWSLambdaVPCAccessExecutionRole"
      VpcConfig:
        SecurityGroupIds: 
         - !Ref SecurityGroupID
        SubnetIds: !Ref SubnetIDs
Outputs:
  NotifyEndpointUsage:
    Description: "Notify Endpoint Usage Lambda Function ARN"
    Value: !GetAtt NotifyEndpointUsage.Arn
