AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app-notification-service

  SAM Template for notification service
  
Parameters:
  ProjectName:
    Type: String
    Default: app-notification-service
  SecurityGroupID:
    Type: String
    NoEcho: true
  SubnetIDs:
    Type: CommaDelimitedList
    NoEcho: true
  RedisEndpoint:
    Type: String
    NoEcho: true
  RedisPort:
    Type: String
    NoEcho: true
  InfluxEndpoint:
    Type: String
    NoEcho: true
  InfluxToken:
    Type: String
    NoEcho: true
  InfluxOrg:
    Type: String
    NoEcho: true
  EmailApiKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 60

Resources:
  NotifyEndpointUsage:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: notify-endpoint-usage
      Description: Notifies of endpoints which overrun the allowed stake
      CodeUri: app/
      Handler: dist/functions/notify-endpoint-usage/app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          EMAIL_API_KEY: !Ref EmailApiKey
          INFLUX_ENDPOINT: !Ref InfluxEndpoint
          INFLUX_TOKEN: !Ref InfluxToken
          INFLUX_ORG: !Ref InfluxOrg
          REDIS_HOST: !Ref RedisEndpoint
          REDIS_PORT: !Ref RedisPort
      Policies:
        - "AWSLambdaVPCAccessExecutionRole"
      VpcConfig:
        SecurityGroupIds: 
         - !Ref SecurityGroupID
        SubnetIds: !Ref SubnetIDs
Outputs:
  NotifyEndpointUsage:
    Description: "Notify Endpoint Usage Lambda Function ARN"
    Value: !GetAtt NotifyEndpointUsage.Arn
