AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app-notification-service

  SAM Template for notification service
  
Parameters:
  ProjectName:
    Type: String
    Default: app-notification-service
  SecurityGroupID:
    Type: String
    NoEcho: true
  # The subnets must be connected through the same vpc as the redis instance (if using elasticache) 
  # and a NAT Gateway in order to have cache and internet access
  SubnetIDs:
    Type: CommaDelimitedList
    NoEcho: true
  RedisEndpoint:
    Type: String
    NoEcho: true
  RedisPort:
    Type: String
    NoEcho: true
  MongoDBConnectionString:
    Type: String
    NoEcho: true
  InfluxEndpoint:
    Type: String
    NoEcho: true
  InfluxToken:
    Type: String
    NoEcho: true
  InfluxOrg:
    Type: String
    NoEcho: true
  EmailApiKey:
    Type: String
    NoEcho: true
  DataDogApiKey:
    Type: String
    NoEcho: true
  DataDogAppKey:
    Type: String
    NoEcho: true
  DataDogSite:
    Type: String
    NoEcho: true
  DiscordToken:
    Type: String
    NoEcho: true
  ChannelId:
    Type: String
    NoEcho: true
  
Globals:
  Function:
    Timeout: 60

Resources:
  NotifyEndpointUsage:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: notify-endpoint-usage
      Description: Notifies of endpoints which overrun the allowed stake
      CodeUri: app/
      Handler: dist/functions/notify-endpoint-usage/app.handler
      Runtime: nodejs14.x
      MemorySize: 500
      Environment:
        Variables:
          EMAIL_API_KEY: !Ref EmailApiKey
          INFLUX_ENDPOINT: !Ref InfluxEndpoint
          INFLUX_TOKEN: !Ref InfluxToken
          INFLUX_ORG: !Ref InfluxOrg
          REDIS_HOST: !Ref RedisEndpoint
          REDIS_PORT: !Ref RedisPort
          MONGODB_CONN_STR: !Ref MongoDBConnectionString
      Policies:
        - "AWSLambdaVPCAccessExecutionRole"
      VpcConfig:
        SecurityGroupIds: 
         - !Ref SecurityGroupID
        SubnetIds: !Ref SubnetIDs
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *)
            Enabled: True
            RetryPolicy:
              MaximumEventAgeInSeconds: 180
              MaximumRetryAttempts: 3

  SendDiscordNotification:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: makefile
    Properties:
      Timeout: 240
      FunctionName: send-discord-notification
      Description: Sends notification to discord on apps/lbs that overran their stake
      CodeUri: app/
      Handler: dist/functions/send-discord-notification/app.handler
      Runtime: nodejs14.x
      MemorySize: 500
      Environment:
        Variables:
          DD_SITE: !Ref DataDogSite
          DD_API_KEY: !Ref DataDogApiKey
          DD_APP_KEY: !Ref DataDogAppKey
          DISCORD_TOKEN: !Ref DiscordToken
          CHANNEL_ID: !Ref ChannelId
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
            Enabled: True
            RetryPolicy:
              MaximumEventAgeInSeconds: 180
              MaximumRetryAttempts: 3
Outputs:
  NotifyEndpointUsage:
    Description: "Notify Endpoint Usage Lambda Function ARN"
    Value: !GetAtt NotifyEndpointUsage.Arn
  SendDiscordNotification:
    Description: "Send Discord Notification Lambda Function ARN"
    Value: !GetAtt SendDiscordNotification.Arn
